ROTATE_X = 0
ROTATE_Y = 1
ROTATE_Z = 2
TRANSLATE_X = 3
TRANSLATE_Y = 4
SHEAR_X = 5
SHEAR_Y = 6
MIRROR_X = 7
MIRROR_Y = 8

operations = (ROTATE_X, ROTATE_Y, ROTATE_Z, TRANSLATE_X, TRANSLATE_Y,SHEAR_X,SHEAR_Y,MIRROR_X, MIRROR_Y)